import re
import json

# Whitelist definition
WHITELIST = {
    'tops': [
        ('basic_tshirt', 'Áo thun basic'),
        ('oversize_tshirt', 'Áo thun oversize'),
        ('croptop', 'Croptop'),
        ('camisole', 'Áo hai dây'),
        ('tank_top', 'Áo tank top'),
        ('blouse', 'Áo blouse'),
        ('shirt', 'Áo sơ mi'),
        ('turtleneck', 'Áo cổ lọ'),
        ('polo', 'Áo polo'),
        ('peplum', 'Áo peplum'),
        ('off_shoulder_top', 'Áo trễ vai'),
        ('sweater', 'Áo len'),
        ('sweatshirt', 'Sweater'),
        ('hoodie', 'Hoodie'),
        ('short_cardigan', 'Cardigan ngắn'),
        ('long_cardigan', 'Cardigan dài'),
        ('corset', 'Áo corset'),
        ('baby_tee', 'Áo baby tee'),
        ('babydoll_top', 'Áo babydoll'),
        ('lace_top', 'Áo kiểu ren'),
    ],
    'bottoms': [
        ('skinny_jeans', 'Quần jean skinny'),
        ('straight_jeans', 'Quần jean ống đứng'),
        ('wide_jeans', 'Quần jean ống rộng'),
        ('baggy_jeans', 'Quần jean baggy'),
        ('denim_shorts', 'Quần short jean'),
        ('kaki_shorts', 'Quần short kaki'),
        ('trousers', 'Quần tây'),
        ('straight_pants', 'Quần ống suông'),
        ('wide_pants', 'Quần ống rộng'),
        ('cargo_pants', 'Quần cargo'),
        ('jogger_pants', 'Quần jogger'),
        ('leggings', 'Quần legging'),
        ('culottes', 'Quần culottes'),
        ('linen_pants', 'Quần linen'),
        ('high_waist_pants', 'Quần cạp cao'),
        ('y2k_pants', 'Quần Y2K'),
        ('sporty_pants', 'Quần sporty'),
        ('leather_pants', 'Quần da'),
    ],
    'skirts': [
        ('aline_skirt', 'Chân váy chữ A'),
        ('tennis_skirt', 'Chân váy tennis'),
        ('pleated_skirt', 'Chân váy xếp ly'),
        ('denim_skirt', 'Chân váy jean'),
        ('midi_skirt', 'Chân váy midi'),
        ('maxi_skirt', 'Chân váy maxi'),
        ('pencil_skirt', 'Chân váy bút chì'),
        ('mermaid_skirt', 'Chân váy đuôi cá'),
        ('satin_skirt', 'Chân váy satin'),
        ('lace_skirt', 'Chân váy ren'),
        ('caro_skirt', 'Chân váy caro'),
        ('cargo_skirt', 'Chân váy cargo'),
        ('mini_skirt', 'Chân váy mini'),
        ('tiered_skirt', 'Chân váy tầng'),
        ('vintage_skirt', 'Chân váy vintage'),
    ],
    'dresses': [
        ('office_dress', 'Đầm công sở'),
        ('bodycon_dress', 'Đầm body'),
        ('party_dress', 'Đầm dự tiệc'),
        ('floral_dress', 'Đầm hoa'),
        ('babydoll_dress', 'Đầm babydoll'),
        ('maxi_dress', 'Đầm maxi'),
        ('midi_dress', 'Đầm midi'),
        ('shirt_dress', 'Đầm sơ mi'),
        ('slip_dress', 'Đầm hai dây'),
        ('off_shoulder_dress', 'Đầm trễ vai'),
        ('square_neck_dress', 'Đầm cổ vuông'),
        ('lace_dress', 'Đầm ren'),
        ('satin_dress', 'Đầm satin'),
        ('sequin_dress', 'Đầm sequin'),
        ('vintage_dress', 'Đầm vintage'),
        ('korean_dress', 'Đầm Korean'),
        ('y2k_dress', 'Đầm Y2K'),
        ('luxury_dress', 'Đầm luxury'),
    ],
    'jackets': [
        ('blazer', 'Blazer'),
        ('denim_jacket', 'Áo khoác jean'),
        ('leather_jacket', 'Áo khoác da'),
        ('bomber_jacket', 'Bomber'),
        ('varsity_jacket', 'Varsity jacket'),
        ('trench_coat', 'Trench coat'),
        ('wool_coat', 'Áo khoác dạ'),
        ('fur_jacket', 'Áo khoác lông'),
        ('outer_cardigan', 'Cardigan khoác ngoài'),
        ('tweed_jacket', 'Áo khoác tweed'),
        ('cropped_jacket', 'Áo khoác cropped'),
        ('oversized_jacket', 'Áo khoác oversized'),
        ('windbreaker', 'Windbreaker'),
        ('varsity_coat', 'Áo khoác varsity'),
        ('sporty_jacket', 'Áo khoác sporty'),
    ],
    'shoes': [
        ('white_sneakers', 'Sneaker trắng'),
        ('chunky_sneakers', 'Sneaker chunky'),
        ('platform_sneakers', 'Sneaker platform'),
        ('pointed_heels', 'Cao gót mũi nhọn'),
        ('strap_heels', 'Cao gót quai mảnh'),
        ('kitten_heels', 'Kitten heels'),
        ('sandals', 'Sandal'),
        ('platform_sandals', 'Sandal platform'),
        ('ankle_boots', 'Boots cổ thấp'),
        ('knee_high_boots', 'Boots cổ cao'),
        ('chelsea_boots', 'Chelsea boots'),
        ('loafers', 'Loafer'),
        ('mary_jane', 'Mary Jane'),
        ('ballet_flats', 'Ballet flats'),
        ('mules', 'Mule'),
        ('oxford_shoes', 'Oxford'),
        ('sport_shoes', 'Giày thể thao'),
        ('luxury_shoes', 'Giày luxury'),
    ],
    'bags': [
        ('tote_bag', 'Túi tote'),
        ('mini_bag', 'Túi mini'),
        ('shoulder_bag', 'Túi đeo vai'),
        ('crossbody_bag', 'Túi đeo chéo'),
        ('baguette_bag', 'Túi baguette'),
        ('bucket_bag', 'Túi bucket'),
        ('office_bag', 'Túi công sở'),
        ('clutch_bag', 'Túi clutch'),
        ('box_bag', 'Túi hộp'),
        ('leather_bag', 'Túi da'),
        ('canvas_bag', 'Túi canvas'),
        ('pastel_bag', 'Túi pastel'),
        ('vintage_bag', 'Túi vintage'),
        ('y2k_bag', 'Túi Y2K'),
        ('luxury_bag', 'Túi luxury'),
        ('bow_bag', 'Túi đính nơ'),
        ('pearl_bag', 'Túi đính ngọc trai'),
    ],
    'accessories': [
        ('sunglasses', 'Kính râm'),
        ('round_glasses', 'Kính gọng tròn'),
        ('baseball_cap', 'Mũ lưỡi trai'),
        ('beret', 'Mũ beret'),
        ('bucket_hat', 'Mũ bucket'),
        ('straw_hat', 'Mũ cói'),
        ('earrings', 'Khuyên tai'),
        ('necklace', 'Vòng cổ'),
        ('bracelet', 'Vòng tay'),
        ('ring', 'Nhẫn'),
        ('belt', 'Thắt lưng'),
        ('hair_clip', 'Kẹp tóc'),
        ('hair_bow', 'Nơ tóc'),
        ('scrunchie', 'Scrunchie'),
        ('headband', 'Băng đô'),
        ('scarf', 'Khăn choàng'),
        ('watch', 'Đồng hồ'),
        ('brooch', 'Brooch'),
        ('pearl_necklace', 'Dây chuyền ngọc trai'),
        ('high_socks', 'Tất cao cổ'),
    ]
}

total = sum(len(v) for v in WHITELIST.values())
print(f'Total Whitelist SubCategories: {total}')
for k, v in WHITELIST.items():
    print(f'  {k}: {len(v)}')
