# Generate accurate sprite mapping report
items = [
  # ROW 1: ĐẦM (Dresses) - 16 items
  (1, 'Đầm sơ mi dáng ngắn màu kem kèm thắt lưng nâu', 'dresses', 'Đầm sơ mi', 'shirt_dress', 'shirt-dress.png', 'Cao'),
  (2, 'Đầm bodycon ôm sát nịt eo màu đỏ quyến rũ', 'dresses', 'Đầm body', 'bodycon_dress', 'bodycon-dress.png', 'Cao'),
  (3, 'Đầm hai dây lụa đen đính nơ trước ngực', 'dresses', 'Đầm hai dây', 'slip_dress', 'slip-dress.png', 'Cao'),
  (4, 'Đầm hoa nhí hồng tay bồng phong cách vintage', 'dresses', 'Đầm hoa', 'floral_dress', 'floral-dress.png', 'Cao'),
  (5, 'Đầm babydoll xòe 2 tầng màu hồng nơ vai', 'dresses', 'Đầm babydoll', 'babydoll_dress', 'babydoll-dress.png', 'Cao'),
  (6, 'Đầm vintage màu kem tà xòe buộc nơ vai', 'dresses', 'Đầm vintage', 'vintage_dress', 'vintage-dress.png', 'Cao'),
  (7, 'Đầm Korean màu xanh dương tay lỡ cổ vuông', 'dresses', 'Đầm Korean', 'korean_dress', 'korean-dress.png', 'Cao'),
  (8, 'Đầm trễ vai màu trắng nhún bèo công chúa', 'dresses', 'Đầm trễ vai', 'off_shoulder_dress', 'off-shoulder-dress.png', 'Cao'),
  (9, 'Đầm cổ vuông màu xanh biển tay ngắn', 'dresses', 'Đầm cổ vuông', 'square_neck_dress', 'square-neck-dress.png', 'Cao'),
  (10, 'Đầm ren đen thêu hoa chìm sang trọng', 'dresses', 'Đầm ren', 'lace_dress', 'lace-dress.png', 'Cao'),
  (11, 'Đầm satin màu hồng dã ngoại bóng mượt', 'dresses', 'Đầm satin', 'satin_dress', 'satin-dress.png', 'Cao'),
  (12, 'Đầm sequin lấp lánh ánh kim dự tiệc', 'dresses', 'Đầm sequin', 'sequin_dress', 'sequin-dress.png', 'Cao'),
  (13, 'Đầm công sở xanh rêu cổ V thắt nơ', 'dresses', 'Đầm công sở', 'office_dress', 'office-dress.png', 'Cao'),
  (14, 'Đầm dự tiệc màu kem đính nơ hồng bồng bềnh', 'dresses', 'Đầm dự tiệc', 'party_dress', 'party-dress.png', 'Cao'),
  (15, 'Đầm midi xòe xanh lam duyên dáng', 'dresses', 'Đầm midi', 'midi_dress', 'midi-dress.png', 'Cao'),
  (16, 'Đầm dạ hội luxury màu đỏ đô kiêu sa', 'dresses', 'Đầm luxury', 'luxury_dress', 'luxury-dress.png', 'Cao'),

  # ROW 2: ÁO KHOÁC (Jackets) - 15 items
  (17, 'Blazer công sở màu be 2 hàng cúc', 'jackets', 'Blazer', 'blazer', 'blazer.png', 'Cao'),
  (18, 'Áo khoác jean xanh denim wash túi ngực', 'jackets', 'Áo khoác jean', 'denim_jacket', 'denim-jacket.png', 'Cao'),
  (19, 'Áo khoác da biker màu đen khóa kéo', 'jackets', 'Áo khoác da', 'leather_jacket', 'leather-jacket.png', 'Cao'),
  (20, 'Áo bomber khoác nhẹ màu hồng pastel', 'jackets', 'Bomber', 'bomber_jacket', 'bomber-jacket.png', 'Cao'),
  (21, 'Varsity jacket đen/trắng thêu logo R', 'jackets', 'Varsity jacket', 'varsity_jacket', 'varsity-jacket.png', 'Cao'),
  (22, 'Trench coat dáng dài màu be thắt lưng', 'jackets', 'Trench coat', 'trench_coat', 'trench-coat.png', 'Cao'),
  (23, 'Áo khoác dạ dài màu trắng sữa cổ bẻ', 'jackets', 'Áo khoác dạ', 'wool_coat', 'wool-coat.png', 'Cao'),
  (24, 'Áo khoác lông bông xù màu kem sang trọng', 'jackets', 'Áo khoác lông', 'fur_jacket', 'fur-jacket.png', 'Cao'),
  (25, 'Cardigan khoác ngoài màu hồng pastel', 'jackets', 'Cardigan khoác ngoài', 'outer_cardigan', 'outer-cardigan.png', 'Cao'),
  (26, 'Áo khoác tweed hồng kẻ caro cúc vàng', 'jackets', 'Áo khoác tweed', 'tweed_jacket', 'tweed-jacket.png', 'Cao'),
  (27, 'Áo khoác cropped jean ngắn lỡ tay', 'jackets', 'Áo khoác cropped', 'cropped_jacket', 'cropped-jacket.png', 'Cao'),
  (28, 'Áo khoác oversized hoodie màu xám đen', 'jackets', 'Áo khoác oversized', 'oversized_jacket', 'oversized-jacket.png', 'Cao'),
  (29, 'Windbreaker áo khoác dù thể thao đen/trắng', 'jackets', 'Windbreaker', 'windbreaker', 'windbreaker.png', 'Cao'),
  (30, 'Áo khoác varsity xanh lá chữ R thể thao', 'jackets', 'Áo khoác varsity', 'varsity_coat', 'varsity-coat.png', 'Cao'),
  (31, 'Áo khoác sporty màu tím viền trắng khóa kéo', 'jackets', 'Áo khoác sporty', 'sporty_jacket', 'sporty-jacket.png', 'Cao'),

  # ROW 3: GIÀY (Shoes) - 16 items
  (32, 'Sneaker platform tím/xanh nhạt đôn đế 5cm', 'shoes', 'Sneaker platform', 'platform_sneakers', 'platform-sneakers.png', 'Cao'),
  (33, 'Sneaker chunky đế thô màu be/kem', 'shoes', 'Sneaker chunky', 'chunky_sneakers', 'chunky-sneakers.png', 'Cao'),
  (34, 'Sneaker trắng viền hồng thể thao', 'shoes', 'Sneaker trắng', 'white_sneakers', 'white-sneakers.png', 'Cao'),
  (35, 'Cao gót quai mảnh màu hồng nữ tính', 'shoes', 'Cao gót quai mảnh', 'strap_heels', 'strap-heels.png', 'Cao'),
  (36, 'Cao gót mũi nhọn màu đen kiêu kỳ', 'shoes', 'Cao gót mũi nhọn', 'pointed_heels', 'pointed-heels.png', 'Cao'),
  (37, 'Kitten heels màu kem nơ nhỏ gót 4cm', 'shoes', 'Kitten heels', 'kitten_heels', 'kitten-heels.png', 'Cao'),
  (38, 'Sandal platform đế xuồng màu be', 'shoes', 'Sandal platform', 'platform_sandals', 'platform-sandals.png', 'Cao'),
  (39, 'Sandal quai ngang đan chéo màu be', 'shoes', 'Sandal', 'sandals', 'sandals.png', 'Cao'),
  (40, 'Mule / Sandal quai đen đế thô cá tính', 'shoes', 'Mule', 'mules', 'mules.png', 'Cao'),
  (41, 'Boots cổ thấp da nâu gót block vintage', 'shoes', 'Boots cổ thấp', 'ankle_boots', 'ankle-boots.png', 'Cao'),
  (42, 'Loafer da đen khóa kim loại mạ vàng', 'shoes', 'Loafer', 'loafers', 'loafers.png', 'Cao'),
  (43, 'Ballet flats giày búp bê hồng gót thấp nơ', 'shoes', 'Ballet flats', 'ballet_flats', 'ballet-flats.png', 'Cao'),
  (44, 'Mary Jane màu kem quai gài cổ chân', 'shoes', 'Mary Jane', 'mary_jane', 'mary-jane.png', 'Cao'),
  (45, 'Oxford da đen buộc dây British style', 'shoes', 'Oxford', 'oxford_shoes', 'oxford-shoes.png', 'Cao'),
  (46, 'Giày thể thao xanh dương chạy bộ', 'shoes', 'Giày thể thao', 'sport_shoes', 'sport-shoes.png', 'Cao'),
  (47, 'Giày luxury màu kem đính đá vương giả', 'shoes', 'Giày luxury', 'luxury_shoes', 'luxury-shoes.png', 'Cao'),

  # ROW 4: TÚI XÁCH (Bags) - 16 items
  (48, 'Túi tote vải canvas màu kem quai xách', 'bags', 'Túi tote', 'tote_bag', 'tote-bag.png', 'Cao'),
  (49, 'Túi mini hồng quai xách tay xinh xắn', 'bags', 'Túi mini', 'mini_bag', 'mini-bag.png', 'Cao'),
  (50, 'Túi công sở da đen khóa nắp mạ vàng', 'bags', 'Túi công sở', 'office_bag', 'office-bag.png', 'Cao'),
  (51, 'Túi đeo chéo da nâu dây dài', 'bags', 'Túi đeo chéo', 'crossbody_bag', 'crossbody-bag.png', 'Cao'),
  (52, 'Túi đeo vai kẹp nách màu trắng kem', 'bags', 'Túi đeo vai', 'shoulder_bag', 'shoulder-bag.png', 'Cao'),
  (53, 'Túi bucket da họa tiết monogram nâu', 'bags', 'Túi bucket', 'bucket_bag', 'bucket-bag.png', 'Cao'),
  (54, 'Túi da đen công sở quai xách vuông', 'bags', 'Túi da', 'leather_bag', 'leather-bag.png', 'Cao'),
  (55, 'Túi canvas thêu hoa voan tinh tế', 'bags', 'Túi canvas', 'canvas_bag', 'canvas-bag.png', 'Cao'),
  (56, 'Túi đính nơ satin màu hồng pastel', 'bags', 'Túi đính nơ', 'bow_bag', 'bow-bag.png', 'Cao'),
  (57, 'Túi vintage da nâu nắp gập khóa đồng', 'bags', 'Túi vintage', 'vintage_bag', 'vintage-bag.png', 'Cao'),
  (58, 'Túi clutch màu kem dây đeo kim loại', 'bags', 'Túi clutch', 'clutch_bag', 'clutch-bag.png', 'Cao'),
  (59, 'Túi hộp vuông da xanh dương mạ vàng', 'bags', 'Túi hộp', 'box_bag', 'box-bag.png', 'Cao'),
  (60, 'Túi pastel nắp gập màu cam nâu nhẹ', 'bags', 'Túi pastel', 'pastel_bag', 'pastel-bag.png', 'Cao'),
  (61, 'Túi Y2K chần bông màu đen xích kim loại', 'bags', 'Túi Y2K', 'y2k_bag', 'y2k-bag.png', 'Cao'),
  (62, 'Túi baguette kẹp nách ánh bạc Y2K', 'bags', 'Túi baguette', 'baguette_bag', 'baguette-bag.png', 'Cao'),
  (63, 'Túi đính ngọc trai tiệc màu hồng điệu đà', 'bags', 'Túi đính ngọc trai', 'pearl_bag', 'pearl-bag.png', 'Cao'),

  # ROW 5 & 6: PHỤ KIỆN (Accessories) - 20 items
  (64, 'Kính râm mắt mèo gọng đen UV400', 'accessories', 'Kính râm', 'sunglasses', 'sunglasses.png', 'Cao'),
  (65, 'Kính gọng tròn kim loại mạ vàng', 'accessories', 'Kính gọng tròn', 'round_glasses', 'round-glasses.png', 'Cao'),
  (66, 'Mũ lưỡi trai màu kem thêu chữ R', 'accessories', 'Mũ lưỡi trai', 'baseball_cap', 'baseball-cap.png', 'Cao'),
  (67, 'Mũ beret nỉ màu hồng tiểu thư Pháp', 'accessories', 'Mũ beret', 'beret', 'beret.png', 'Cao'),
  (68, 'Mũ bucket canvas màu đen đính logo', 'accessories', 'Mũ bucket', 'bucket_hat', 'bucket-hat.png', 'Cao'),
  (69, 'Mũ cói rộng vành đi biển thắt nơ đen', 'accessories', 'Mũ cói', 'straw_hat', 'straw-hat.png', 'Cao'),
  (70, 'Khuyên tai ngọc trai giọt nước đôi', 'accessories', 'Khuyên tai', 'earrings', 'earrings.png', 'Cao'),
  (71, 'Dây chuyền ngọc trai chuỗi tròn vương giả', 'accessories', 'Dây chuyền ngọc trai', 'pearl_necklace', 'pearl-necklace.png', 'Cao'),
  (72, 'Vòng cổ dây chuyền ngọc trai đen đính nơ', 'accessories', 'Vòng cổ', 'necklace', 'necklace.png', 'Cao'),
  (73, 'Vòng tay hạt ngọc trai tròn sang trọng', 'accessories', 'Vòng tay', 'bracelet', 'bracelet.png', 'Cao'),
  (74, 'Set 3 nhẫn kim loại mạ vàng minimal', 'accessories', 'Nhẫn', 'ring', 'ring.png', 'Cao'),
  (75, 'Thắt lưng da đen khóa vuông mạ vàng', 'accessories', 'Thắt lưng', 'belt', 'belt.png', 'Cao'),
  (76, 'Kẹp tóc mạ vàng tạo hình sóng lá', 'accessories', 'Kẹp tóc', 'hair_clip', 'hair-clip.png', 'Cao'),
  (77, 'Khăn choàng len kẻ caro đỏ trắng giữ ấm', 'accessories', 'Khăn choàng', 'scarf', 'scarf.png', 'Cao'),
  (78, 'Đồng hồ kim loại mạ vàng hồng quý phái', 'accessories', 'Đồng hồ', 'watch', 'watch.png', 'Cao'),
  (79, 'Băng đô nơ lụa đính ngọc trai', 'accessories', 'Băng đô', 'headband', 'headband.png', 'Cao'),
  (80, 'Brooch cài áo nơ đen đính đá ngọc trai', 'accessories', 'Brooch', 'brooch', 'brooch.png', 'Cao'),
  (81, 'Nơ tóc lụa ruy băng đỏ ngọt ngào', 'accessories', 'Nơ tóc', 'hair_bow', 'hair-bow.png', 'Cao'),
  (82, 'Scrunchie vải nhung hồng buộc tóc', 'accessories', 'Scrunchie', 'scrunchie', 'scrunchie.png', 'Cao'),
  (83, 'Tất cao cổ sọc ngang đen/trắng & tất viền ren', 'accessories', 'Tất cao cổ', 'high_socks', 'high-socks.png', 'Cao'),
]

print(f"Total mapped items: {len(items)}")
